### ISSUE TITLE
Whitespace complains about multi-line if statements

### ISSUE THREAD

**Issue by Zamiell** [ultraware/whitespace#1]
Greetings. `whitespace` complains about the following if statement, claiming that it has a "unnecessary leading newline":

```
# Multi-line if statement 1
if condition1ThatisReallyLong &&
	condition2ThatisReallyLong &&
	condition3ThatisReallyLong &&
	condition4ThatisReallyLong {

	foo()
}
```

However, this does not appear to be true - doesn't it have a **trailing** newline instead of a leading newline? (This appears to be a bug.)

Furthermore, `whitespace` does **not** complain about the following if statement:

```
# Multi-line if statement 2
if condition1ThatisReallyLong &&
	condition2ThatisReallyLong &&
	condition3ThatisReallyLong &&
	condition4ThatisReallyLong {
	foo()
}
```

Is complaining about the former but not the latter the intended behavior?

From a coding style perspective, I submit that the first multi-line if statement should be preferred - it helps distinguish between the conditionals and the block code. (Furthermore, this style strikes me as the conventional Golang standard, although I have no empirical data with which to back up that claim. `gofmt` seems to be fine with both styles.)

**Comment by NiseVoid** [comment]
The message it's giving is correct, as it's a leaing newline in this code block (anything surrounded by `{}`).

However I agree there is a case to be made about the readability, it would be interesting to see how this is handled in Go's source code. Sadly gofmt can't be used as an example since it doesn't seem to have an opinion about single newlines.

**Comment by NiseVoid** [comment]
I took a look at multi-line if statements in the Go source code. There were no cases with an extra newline. Half of them did have a comment after the if, which achieves similar readability.

**Comment by Zamiell** [comment]
Can you link some cases? How did you find them? Is there a command-line way to search through a repo for multi line if statements?

**Comment by NiseVoid** [comment]
I used a simple grep command to find some cases:

```bash
grep -A5 "if .* &&$" $(find /usr/lib/go/src -name "*.go")
```

This command is not perfect as it misses many case, but I'd say there's plenty of examples with this one command

**Comment by Zamiell** [comment]
Thanks. I used this grep statement on the Kubernetes repository. Similar to the Golang repository, they also do not seem to use any newline between conditionals and more code, which was honestly surprising to me.

With that said, there is still a case to be made for programmers preferring a newline here for easy readability. Should `whitespace` be updated to ignore this specific kind of newline?

**Comment by NiseVoid** [comment]
Ignoring the newlines sounds like a bad solution. It could lead to inconsistent code. A better solution would be to make a setting that gives a warning when there is no newline (or comment) after every multi-line if.

**Comment by Zamiell** [comment]
That would be great, thank you.

**Comment by NiseVoid** [comment]
I added a setting for this feature and made a pull request on golangci-lint.

https://github.com/golangci/golangci-lint/pull/723

**Comment by Zamiell** [comment]
Thank you!!
