### ISSUE TITLE
should not complain about unnecessary whitespace if func decleration is spread over multiple lines

### ISSUE THREAD

**Issue by ghost** [ultraware/whitespace#2]
https://github.com/anz-bank/sysl/blob/master/sysl2/sysl/parse/parse.go#L316 is triggering this new linter to complain about the empty line between the func line and the code. In my opinion, removing that empty line makes this much less readable (in that the code gets lost in the parameter list).

https://github.com/anz-bank/sysl/blob/8e4fac991a393c5af362e83ab0a0687fbcb23dd6/sysl2/sysl/sysl.go#L76 on the other-hand is a reasonable error.

Can you please allow this construct (or add a configuration option to allow it?)

**Comment by NiseVoid** [comment]
Similar to the multi-line if statement issue, I added a setting that will enforce a newline after a multi-line function declaration.

I opened a PR on golangci-lint to update it to the new version. https://github.com/golangci/golangci-lint/pull/786

**Comment by ghost** [comment]
Awesome! Thanks
