### ISSUE TITLE
Option to ignore newline in functions

### ISSUE THREAD

**Issue by utdrmac** [ultraware/whitespace#4]
This is completely opinion-based. I find this:

```
func CryptoGenericHash(buffer string, watermark []byte) ([]byte, error) {
	// Convert hex buffer to bytes
	bufferBytes, err := hex.DecodeString(buffer)
	if err != nil {
		return []byte{0}, errors.Wrap(err, "Unable to hex decode buffer bytes")
	}
}
```

more cumbersome to read than this:

```
func CryptoGenericHash(buffer string, watermark []byte) ([]byte, error) {

	// Convert hex buffer to bytes
	bufferBytes, err := hex.DecodeString(buffer)
	if err != nil {
		return []byte{0}, errors.Wrap(err, "Unable to hex decode buffer bytes")
	}
}
```

I really enjoy having that blank space right after func declarations. My code seems less "cluttered" with that spacing. Is there a way to disable this specific check but keep the others?

**Comment by NiseVoid** [comment]
There is currently no way to skip this check for only functions, except with multiline function declarations. However, the error is placed on the line of the function which allows you to ignore this specific situation with `exclude-rules` in your .golangci.yml like this:

```yaml
issues:
  exclude-rules:
    - linters:
        - whitespace
      source: "^func "
```
