### ISSUE TITLE
Suggestion: Don't lint leading empty line after function using multiple lines

### ISSUE THREAD

**Issue by tehsphinx** [ultraware/whitespace#5]
Suggestion: Ignore (or option to ignore) empty line after a function declaration that takes more than a single line. If the empty line is removed after, it makes it a lot harder to read.

Sample:

```go
// Connect connects to the scylla database.
func Connect(ctx context.Context, connStrs []string, user string, pass string, keyspace string,
	tlsCa string, clientCert string, clientKey string) (*Conn, error) {

	conn, err := scylla.Connect(connStrs, user, pass, keyspace, tlsCa, clientCert, clientKey)
	if err != nil { ... }
}
```

**Comment by NiseVoid** [comment]
You can make whitespace require a newline after a multi-line function declaration (or if statement) by setting multi-func (or multi-if for if statements) in your `.golangci.yml`, would this be sufficient for your usecase?

Config example:
```yaml
linters-settings:
  whitespace:
    multi-func: true
    multi-if: true
```

**Comment by tehsphinx** [comment]
@NiseVoid: Yes, that sounds awesome! 🚀 

(sry, must have overlooked your response back in 2021)
