### ISSUE TITLE
Inline function not recognized as multi-line function

### ISSUE THREAD

**Issue by guggero** [ultraware/whitespace#6]
Thank you for this linter plugin! This is exactly what I've been looking for.
Unfortunately there seems to be a bug which causes the "insert blank line after multi-line function definition" not to work for inline functions. 

Settings:

```
linters-settings:
  whitespace:
    multi-func: true
    multi-if: true
```

Code as I want it to look in my projects:

```go
func Example1() {
	inlineFunction := func(veryLongArgumentName *withALongType,
		secondArgument *anotherLongType) {

		// Code or comments should start after an empty line here.
	}
}

func Example2() {
	testCases := []struct {
		name   string
		caseFn func(*testing.T, *someLongType, *fooBar) error
	}{
		{
			name:   "example",
			caseFn: func(t *testing.T, myLongVar *someLongType,
				myOtherVar *fooBar) error {

				// Code or comments should start after an
				// empty line here.
				return nil
			}
		},
	}
}
```

But on both cases the linter complains about the blank line before the `// Code or comments should start after an empty line here` comment.

**Comment by NiseVoid** [comment]
Thanks for your bug report. I could reproduce the problem with your examples, it turned out whitespace didn't apply the multi-func logic to function literals. I've pushed a fix. When it is included in golangci-lint this should be fixed.

**Comment by guggero** [comment]
Thank you very much for the fix! Can confirm this works as expected now in https://github.com/ultraware/whitespace/releases/tag/v0.0.5.
Going to create a PR in golangci-lint to pull in this new version.
